<?php $cohort = $this->getCohort(); ?>

<div class="entry-edit-head collapseable">
    <a id="cohort_<?php echo $cohort ?>_name-head" href="#" class="open" onclick="Fieldset.toggleCollapse('cohort_<?php echo $cohort ?>_name'); return false;">Name</a>
    <?php if ($this->getCohort() == 'Control'): ?>
    <input type="hidden" name="cohort[<?php echo $cohort ?>][is_control]" value="1" />
    <?php else: ?>
    <input type="hidden" name="cohort[<?php echo $cohort ?>][is_control]" value="0" />
    <?php endif; ?>
    <input type="hidden" name="cohort[<?php echo $cohort ?>][split_percentage]" id="cohort_<?php echo $cohort ?>_percentage" value="<?php if($this->getCohort() == 'Control') echo "70"; if ($this->getCohort() == 'A') echo "30"; ?>" />
</div>
<div class="fieldset" id="cohort_<?php echo $cohort ?>_name">
    <div class="hor-scroll">
        <table cellspacing="0" class="form-list">
        <tbody>
            <tr>
                <td class="label"><label for="cohort_<?php echo $cohort ?>_name">Name <span class="required">*</span></label></td>
                <td class="value">
                <?php if ($this->getCohort() == 'Control'): ?>
                    <input type="text" name="cohort[<?php echo $cohort ?>][name]" id="cohort_<?php echo $cohort ?>_name" value="Control" class="required-entry input-text cohort-name" />
                <?php else: ?>
                <input type="text" name="cohort[<?php echo $cohort ?>][name]" id="cohort_<?php echo $cohort ?>_name" value="Variation <?php echo $cohort ?>" class="required-entry input-text cohort-name" />
                <?php endif; ?>
                </td>
            </tr>
        </tbody>
        </table>
    </div>
</div>
<script>$('cohort_<?php echo $cohort ?>_name-head').collapsed = 0;</script>

<div class="entry-edit-head collapseable">
    <a id="cohort_<?php echo $cohort ?>_xml-head" href="#" class="open" onclick="Fieldset.toggleCollapse('cohort_<?php echo $cohort ?>_xml'); return false;">XML Layout Updates</a>
</div>
<div class="fieldset" id="cohort_<?php echo $cohort ?>_xml">
    <div class="hor-scroll">
        <table cellspacing="0" class="form-list" style="width:100%; margin-top: 10px;">
        <tbody>
            <tr>
                <td class="value">
                    XML Layout Updates<?php if ($this->getCohort() == 'Control'): ?> (typically left blank for the control)<?php endif; ?>:
                    <button title="Reset" type="button" data-cohort="cohort_<?php echo $cohort ?>" style="float: right" class="scalable preview-xml" style=""><span>Preview variation</span></button>
                </td>
            </tr>
            <tr>
                <td class="value">
                    <textarea name="cohort[<?php echo $cohort ?>][layout_update]" id="cohort_<?php echo $cohort ?>_xml" value="" style="width: 99.5%;font-family:monospace; height: 25em" class="input-text"></textarea>
                </td>
            </tr>
        </tbody>
        </table>
    </div>
</div>
<script>$('cohort_<?php echo $cohort ?>_xml-head').collapsed = 0;</script>

<div class="entry-edit-head collapseable">
    <a id="cohort_<?php echo $cohort ?>_theme-head" href="#" class="open" onclick="Fieldset.toggleCollapse('cohort_<?php echo $cohort ?>_theme'); return false;">Theme</a>
</div>
<div class="fieldset" id="cohort_<?php echo $cohort ?>_theme">
    <div class="hor-scroll">
        <table cellspacing="0" class="form-list">
        <tbody>
            <tr>
                <td class="label"><label for="cohort_<?php echo $cohort ?>_theme">Theme (leave blank for the current theme)</label></td>
                <td class="value">
                    <input type="text" name="cohort[<?php echo $cohort ?>][theme]" id="cohort_<?php echo $cohort ?>_theme" value="" class="input-text cohort-theme" />
                </td>
            </tr>
        </tbody>
        </table>
    </div>
</div>
<script>$('cohort_<?php echo $cohort ?>_theme-head').collapsed = 0;</script>
