<div class="entry-edit-head">
    <?php if ($this->getCohort() == 'Control'): ?>
        <h4 class="icon-head head-edit-form fieldset-legend cohort-label cohort_Control_name"><span>Control</span></h4>
        <input type="hidden" name="cohort[<?php echo $this->getCohort(); ?>][is_control]" value="1" />
    <?php else: ?>
        <h4 class="icon-head head-edit-form fieldset-legend cohort-label cohort_<?php echo $this->getCohort(); ?>_name"><span>Variation <?php echo $this->getCohort() ?></span></h4>
        <input type="hidden" name="cohort[<?php echo $this->getCohort(); ?>][is_control]" value="0" />
    <?php endif; ?>

    <input type="hidden" name="cohort[<?php echo $this->getCohort(); ?>][split_percentage]" id="cohort_<?php echo $this->getCohort(); ?>_percentage" value="<?php if($this->getCohort() == 'Control') echo "70"; if ($this->getCohort() == 'A') echo "30"; ?>" />

</div>
<div class="form-buttons"></div>
<div class="fieldset" id="date_fieldset">
    <div class="hor-scroll">
        <table cellspacing="0" class="form-list">
        <tbody>
            <tr>
                <td class="label"><label for="cohort_<?php echo $this->getCohort(); ?>_name">Name <span class="required">*</span></label></td>
                <td class="value">
                <?php if ($this->getCohort() == 'Control'): ?>
                    <input type="text" name="cohort[<?php echo $this->getCohort(); ?>][name]" id="cohort_<?php echo $this->getCohort(); ?>_name" value="Control" class="required-entry input-text cohort-name" />
                <?php else: ?>
                    <input type="text" name="cohort[<?php echo $this->getCohort(); ?>][name]" id="cohort_<?php echo $this->getCohort(); ?>_name" value="Variation <?php echo $this->getCohort(); ?>" class="required-entry input-text cohort-name" />
                <?php endif; ?>
                </td>
            </tr>
            <tr>
                <td class="label"><label for="cohort_<?php echo $this->getCohort(); ?>_theme">Theme (leave blank for the current theme)</label></td>
                <td class="value">
                    <input type="text" name="cohort[<?php echo $this->getCohort(); ?>][theme]" id="cohort_<?php echo $this->getCohort(); ?>_theme" value="" class="input-text cohort-theme" />
                </td>
            </tr>
        </tbody>
        </table>
        <table cellspacing="0" class="form-list" style="width:100%; margin-top: 10px;">
        <tbody>
            <tr>
                <td class="value">
                    Layout Update XML<?php if ($this->getCohort() == 'Control'): ?> (typically left blank for the control)<?php endif; ?>:
                    <button title="Reset" type="button" data-cohort="cohort_<?php echo $this->getCohort(); ?>" style="float: right" class="scalable preview-xml" style=""><span><span><span>Preview</span></span></span></button>
                </td>
            </tr>
            <tr>
                <td class="value">
                    <textarea name="cohort[<?php echo $this->getCohort(); ?>][layout_update]" id="cohort_<?php echo $this->getCohort() ?>_xml" value="" style="width: 99.5%;font-family:monospace; height: 25em" class="input-text"></textarea>
                </td>
            </tr>
        </tbody>
        </table>
    </div>
</div>
