<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend">Date settings</h4>
    <div class="form-buttons"></div>
</div>
<div class="form-buttons"></div>
<div class="fieldset " id="date_fieldset">
    <div class="hor-scroll">
        <table cellspacing="0" class="form-list">
        <tbody>
            <tr>
                <td class="label"><label for="el_test_name">Name <span class="required">*</span></label></td>
                <td class="value">
                    <input type="text" name="test[name]" id="el_test_name" value="" class="required-entry input-text" />
                </td>
            </tr>
            <tr>
                <td class="label"><label for="el_test_description">Description</label></td>
                <td class="value">
                    <textarea name="test[description]" id="el_test_description" value="" style="height: 5em" class="input-text"></textarea>
                </td>
            </tr>
            <tr>
                <td class="label"><label for="el_start_date">Start date <span class="required">*</span></label></td>
                <td class="value">
                <input name="test[start_date]" id="el_start_date" value="<?php echo Date("d/m/Y", time()); ?>" style="width: 200px" type="text" class=" required-entry input-text"> <img src="http://magento.local/skin/adminhtml/default/default/images/grid-cal.gif" alt="" class="v-middle" id="el_start_date_trig" title="Select Date" style="">
                    <script type="text/javascript">
                    //<![CDATA[
                        Calendar.setup({
                            inputField: "el_start_date",
                            ifFormat: "%e/%m/%Y",
                            showsTime: true,
                            button: "el_start_date_trig",
                            align: "Bl",
                            singleClick : true
                        });
                    //]]>
                    </script>
                </td>
            </tr>
            <tr>
                <td class="label"><label for="el_end_date">End date</label></td>
                <td class="value">
                    <input name="test[end_date]" id="el_end_date" value="" style="width: 200px" type="text" class=" input-text"> <img src="http://magento.local/skin/adminhtml/default/default/images/grid-cal.gif" alt="" class="v-middle" id="el_end_date_trig" title="Select Date" style="">
                    <script type="text/javascript">
                    //<![CDATA[
                        Calendar.setup({
                            inputField: "el_end_date",
                            ifFormat: "%e/%m/%Y",
                            showsTime: true,
                            button: "el_end_date_trig",
                            align: "Bl",
                            singleClick : true
                        });
                    //]]>
                    </script>
                    <p class="note" id="note_el_end_date"><span>Leave blank to leave running indefinitely</span></p>
                </td>
            </tr>
        </tbody>
        </table>
    </div>
</div>

<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend">A/B Test Settings</h4>
    <div class="form-buttons"></div>
</div>
<div class="fieldset " id="observer_fieldset">
    <div class="hor-scroll">
        <table cellspacing="0" class="form-list">
        <tbody>
            <tr>
                <td class="label"><label for="el_target_observer">Test page <span class="required">*</span></label></td>
                <td class="value">
                    <select id="el_target_observer" name="test[observer_target]" style="width: 300px" class=" required-entry select">
                        <option value="catalog_controller_product_view">Product page</option>
                        <option value="catalog_controller_category_init_before">Category page</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="label"><label for="el_conversion_observer">Conversion action <span class="required">*</span></label></td>
                <td class="value">
                    <select id="el_conversion_observer" name="test[observer_conversion]" style="width: 300px" class=" required-entry select">
                        <option value="checkout_cart_add_product_complete">Added product to cart</option>
                        <option value="checkout_onepage_controller_success_action">Completed checkout</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="label"><label for="el_cohorts">Variations <span class="required">*</span></label></td>
                <td class="value">
                    <select id="el_cohorts" name="cohorts" style="width: 300px" class=" required-entry select">
                        <option value="2">1</option>
                        <option value="3">2</option>
                        <option value="4">3</option>
                        <option value="5">4</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="label"><label for="el_control_traffic">Control traffic percentage <span class="required">*</span></label></td>
                <td class="value">
                    <input type="text" name="el_control_traffic" id="el_control_traffic" value="70" class="required-entry input-text" style="width:2.5em" /> % &nbsp;<a href="#" id="split_traffic_evenly">(split evenly)</a>
                    <p class="note" id="note_el_control_traffic"><span>The variation gets <b>30%</b> of the traffic</span></p>
                </td>
            </tr>
        </tbody>
        </table>
    </div>
</div>
